Search for similar questions using tf idf
JetBrains-Research/stepik-comment-analysis pull request #1
Opened 2021-07-13 06:44 UTC by anastasia-kozlova

2021-07-13 10:21 UTC, SpirinEgor requested changes

2021-07-13 10:21 UTC, SpirinEgor commented on src/config.py
> +DATA_DIR = ROOT_DIR / "data"
Лучше os.path.join использовать

2021-07-13 10:21 UTC, SpirinEgor commented on src/execution.py
> +STEP_ID = 6532
А для чего мы фиксируем id?

2021-07-13 10:21 UTC, SpirinEgor commented on src/execution.py
> +df_comm = load_data.load_comments()
Такой скрипт будет трудно переиспользовать, например, из ноутбука. Лучше всего сделать так:

```
def execute(step_id: int) -> List:
    ...
    return pair_indexes
    
if __name__ == "__main__":
    print(execute(STEP_ID))
```

2021-07-13 10:21 UTC, SpirinEgor commented on src/execution.py
> +df_comm = load_data.load_comments()
execute, конечно, лучше на что-то более адекватное заменить

2021-07-13 10:21 UTC, SpirinEgor commented on src/load_data.py
> +STEPS_FILE_NAME = config.STEPS_FILE_NAME
```
from config import DATA_DIR, COMMENTS_FILE_NAME, STEPS_FILE_NAME
```

2021-07-13 10:21 UTC, SpirinEgor commented on src/load_data.py
> +def load_comments():
А еще лучше в этом файле избавиться от путей глобальных. Пусть этот будет параметр
```
def load_comments(filepath: str) -> DataFrame:
    ....
```

2021-07-13 10:21 UTC, SpirinEgor commented on src/load_data.py
> +    df = pd.read_csv(DATA_DIR / COMMENTS_FILE_NAME, compression="gzip")
join надо использовать

2021-07-13 10:21 UTC, SpirinEgor commented on src/load_data.py
> +def load_steps():
Тут аналогично про путь к файлу и join

2021-07-13 10:21 UTC, SpirinEgor commented on src/preprocessing.py
> +        if any(word in PATTERN for word in text):
Можешь заменить на регулярку?
```
PATTERN = r"\?|(проблема)|(почему)"
...
if re.search(PATTERN, text):
    ....
```

2021-07-13 10:21 UTC, SpirinEgor commented on src/preprocessing.py
> +            text = [word for word in text if "?" not in word]
А зачем?

2021-07-13 10:21 UTC, SpirinEgor commented on src/preprocessing.py
> +    questions_dict = {k: v for k, v in enumerate(questions_idx)}
А это зачем?

2021-07-13 10:21 UTC, SpirinEgor commented on src/preprocessing.py
> +class Cleaner:
Может имеет смысл регулярно разово скомпилить и сделать полями класса?

2021-07-13 11:04 UTC, anastasia-kozlova commented on src/execution.py
> +STEP_ID = 6532
Natasha работает дико долго, поэтому запускаю по очереди.

2021-07-13 11:12 UTC, anastasia-kozlova commented on src/preprocessing.py
> +            text = [word for word in text if "?" not in word]
После чистки комментарии могут состоять только из одних "?", которые потом помечаются как похожие.

2021-07-13 11:16 UTC, anastasia-kozlova commented on src/preprocessing.py
> +    questions_dict = {k: v for k, v in enumerate(questions_idx)}
Мы сохраняем ключи к нашим комментариям. У нас был массив со всеми комментариями первого уровня, но после отбора у нас уже новый массив, состоящий из вопросов.

2021-07-13 11:18 UTC, anastasia-kozlova commented on src/preprocessing.py
> +class Cleaner:
Не понимаю(( Про какой класс ты говоришь?

2021-07-16 08:06 UTC, SpirinEgor approved these changes

2021-07-16 08:06 UTC, merged